### PR TITLE
Fix default matching pattern

### LINKED ISSUE #138: Retest defaults to `test_*.rb` pattern even when `*_test.rb` file exists
Here is the original issue

* When updating the file `test_options.rb` 
* I expect retest to select `test_options_test.rb` 
* and not to return the file `test_options.rb`

I think this is also related to this issue:

* Given there are three files `test_fixtures.rb`, `fixtures.rb` and `fixtures_test.rb`
* A change in `fixtures.rb` selects `test_fixtures.rb` by default 
* When it should offer the option to choose between `test_fixtures.rb` and `fixtures_test.rb`

When a file is discovered with the pattern `test_*.rb` we do not continue searching for other file patterns which could potentially be more appropriate.

### PR DESCRIPTION
**Pull request by AlexB52**
Fixes #138

### CODE REVIEW

File: lib/retest/matching_options/path.rb [hunk 1]
```diff
@@ -30,6 +38,10 @@ def similarity_score(file)
 
       private
 
+      def root_file?
+        dirnames == %w[.]
```
Comment (AlexB52) [inline lib/retest/matching_options/path.rb:42]: not a fan of this conditional maybe we can add "." as a test directory instead.

Comment (AlexB52) [reply lib/retest/matching_options/path.rb:46]: Wasn't able to :(
