### PR TITLE
Set Runner last command on initialization

### LINKED ISSUE #240: Fix Kernel system type error when hitting enter upon boot
## Why

Hello. :wave: I'm seeing an issue where upon initial launch of `retest` -- and hitting <kbd>ENTER</kbd> -- will cause the following exception:

``` 
Setup identified: [RSPEC]. Using command: 'bin/rspec <test>'
Watcher: [LISTEN]
Launching Retest...
Ready to refactor! You can make file changes now

Type interactive command and press enter. Enter 'h' for help.
>
Running last command: ''

/Users/bkuhlmann/.cache/frum/versions/3.4.1/lib/ruby/gems/3.4.0/gems/retest-2.0.0/lib/retest/runner.rb:88:in 'Kernel#system': no implicit conversion of nil into String (TypeError)

      result = system(command) ? :tests_pass : :tests_fail
                      ^^^^^^^
	from /Users/bkuhlmann/.cache/frum/versions/3.4.1/lib/ruby/gems/3.4.0/gems/retest-2.0.0/lib/retest/runner.rb:88:in 'Retest::Runner#system_run'
	from /Users/bkuhlmann/.cache/frum/versions/3.4.1/lib/ruby/gems/3.4.0/gems/retest-2.0.0/lib/retest/runner.rb:18:in 'Retest::Runner#run_last_command'
	from /Users/bkuhlmann/.cache/frum/versions/3.4.1/lib/ruby/3.4.0/forwardable.rb:240:in 'Retest::Program#run_last_command'
	from /Users/bkuhlmann/.cache/frum/versions/3.4.1/lib/ruby/gems/3.4.0/gems/retest-2.0.0/exe/retest:100:in 'Object#run_command'
	from /Users/bkuhlmann/.cache/frum/versions/3.4.1/lib/ruby/gems/3.4.0/gems/retest-2.0.0/exe/retest:136:in 'block (2 levels) in <top (required)>'
	from /Users/bkuhlmann/.cache/frum/versions/3.4.1/lib/ruby/gems/3.4.0/gems/retest-2.0.0/exe/retest:134:in 'Array#each'
	from /Users/bkuhlmann/.cache/frum/versions/3.4.1/lib/ruby/gems/3.4.0/gems/retest-2.0.0/exe/retest:134:in 'block in <top (required)>'
	from <internal:kernel>:168:in 'Kernel#loop'
	from /Users/bkuhlmann/.cache/frum/versions/3.4.1/lib/ruby/gems/3.4.0/gems/retest-2.0.0/exe/retest:128:in '<top (required)>'
	from /var/folders/yn/zk8yhvr1593bbyy_v77zjmg00000gn/T/frum_1678_1735397815355/bin/retest:25:in 'Kernel#load'
	from /var/folders/yn/zk8yhvr1593bbyy_v77zjmg00000gn/T/frum_1678_1735397815355/bin/retest:25:in '<main>'
```

## How

To recreate, launch `retest` in any project and immediately hit <kbd>ENTER</kbd> to recreate the above. The workaround is to run `ra` from the `restest` command prompt to _seed_ it with information and the problem goes away. This _only_ happens upon initial launch.

I'm guessing you'd want to ensure the `command` being passed to `system` defaults to `ra` as that is the default behavior when hitting <kbd>ENTER</kbd> once `retest` is fully initialized.

## Notes

- **Operating System**: macOS 15.2
- **Ruby**: ruby 3.4.1 (2024-12-25 revision 48d4efcb85) +YJIT +PRISM [arm64-darwin24.2.0]
- **Retest**: 2.0.0

### PR DESCRIPTION
**Pull request by AlexB52**
Fixes #240 

Sets runner's last command during initialisation when the command is runnable (e.g. with no placeholders)

### CODE REVIEW

File: lib/retest/runner.rb [hunk 1]
```diff
@@ -12,15 +12,22 @@ class Runner
...
       @stdout  = stdout
       @command = command
+      if command.hardcoded?
+        self.last_command = command.to_s
+      end
     end
 
     def run_last_command
+      unless last_command
+        return log('Error - Not enough information to trigger a run')
```
Comment (AlexB52) [inline lib/retest/runner.rb:22]: Change to `Error - Not enough information to run a command. Please trigger a run first.` maybe

File: test/retest/runner_test.rb
Comment (AlexB52) [inline test/retest/runner_test.rb:1]: Is it worth a feature specs for this bugfix
